---
# - name: Include vars file
#   include_vars:
#     file: "{{ vars_file }}"
- name: get vars file 
  command: bash "{{ playbook_dir }}/{{ vars_file }}"
  delegate_to: localhost 
  register: vars_file_output

# - name: Debug var
#   debug:
#     var: vars_file_output
- name: 动态加载变量文件
  set_fact:
    httpiconfig:  "{{ vars_file_output.stdout  | from_yaml }}"


- name: Deploy and validate NGINX configuration
  block:
    - name: Ensure NGINX HTTP directory exists
      ansible.builtin.file:
        # path: "{{ item['deployment_location'] | default('/etc/nginx/conf.d/') | dirname }}"
        path: "/tmp/{{ item['deployment_location'] | default('/etc/nginx/conf.d/') | dirname }}"
        state: directory
        mode: "0755"
      loop: "{{ httpiconfig.nginx_config_http_template }}"
      loop_control:
        label: "{{ item['deployment_location'] | default('/etc/nginx/conf.d/') | dirname }}"
      when: httpiconfig.nginx_config_http_template_enable | bool
    - name: Dynamically generate NGINX HTTP config files
      ansible.builtin.template:
        src: "{{ item['template_file'] | default('http/default.conf.j2') }}"
        dest: "/tmp/{{ item['deployment_location'] | default('/etc/nginx/conf.d/default.conf') }}"
        backup: "{{ item['backup'] | default(true) }}"
        mode: "0644"
      loop: "{{ httpiconfig.nginx_config_http_template }}"
      loop_control:
        label: "{{ item['deployment_location'] | default('/etc/nginx/conf.d/default.conf') }}"
      when: httpiconfig.nginx_config_http_template_enable | bool 
      register: http_config_result
    - name: cat http config 
      command: "cat /tmp/{{ item['deployment_location'] }} "
      loop: "{{ httpiconfig.nginx_config_http_template }}"
      loop_control:
        label: "/tmp/{{ item['deployment_location'] | default('/etc/nginx/conf.d/default.conf') }}"
      when: httpiconfig.nginx_config_http_template_enable | bool 
      register: command_output    
    # - name: Print to console
    #   debug: 
    #     mes:  command_output
    #   # loop: "{{ command_output.results }}"
    #   # loop_control:
    #   #   label:
    - name: config is 
      debug:
        msg: "{{ item.stdout_lines }}"  
      loop: "{{ command_output.results }}"
      loop_control:
        label: "/tmp/{{ item.item.deployment_location  }}"
    - name: diff http config 
      command:
        diff "/tmp/{{ item['deployment_location'] }}"  {{ item['deployment_location'] }}
      loop: "{{ httpiconfig.nginx_config_http_template }}"
      loop_control:
        label: "{{ item['deployment_location'] | default('/etc/nginx/conf.d/default.conf') }}"
      when: httpiconfig.nginx_config_http_template_enable | bool 
